# Generated by Django 5.2.17 on 2026-10-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'bloque horario',
                'verbose_name_plural': 'bloques horarios',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='CentroTerapeutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Aquí Somos Sensoriales', max_length=120)),
                ('horas_minimas_cancelacion', models.PositiveSmallIntegerField(default=24, verbose_name='horas mínimas de anticipación para cancelar')),
                ('duracion_bloque', models.PositiveSmallIntegerField(default=45, verbose_name='duración estándar del bloque (minutos)')),
            ],
            options={
                'verbose_name': 'centro terapéutico',
                'verbose_name_plural': 'centro terapéutico',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('CONFIRMADA', 'Confirmada'), ('REALIZADA', 'Realizada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=15)),
                ('motivo_consulta', models.CharField(help_text='Ej: Terapia Ocupacional, Integración Sensorial, Evaluación TEA, Primera Consulta', max_length=300, verbose_name='motivo de consulta')),
                ('mensaje_sensorial', models.TextField(blank=True, help_text='Indica hipersensibilidad (auditiva, táctil), requerimientos de luz, límites de tiempo o adaptaciones', verbose_name='mensaje de introducción y perfil sensorial')),
                ('motivo_respuesta', models.CharField(blank=True, max_length=300, verbose_name='motivo de respuesta o cancelación')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'ordering': ['bloque__inicio'],
            },
        ),
    ]
