# Generated by Django 5.2.17 on 2026-10-09 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquehorario',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='bloque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='agenda.bloquehorario'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_paciente', to=settings.AUTH_USER_MODEL),
        ),
    ]
