# Generated by Django 5.2.17 on 2026-10-09 03:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('rol', models.CharField(choices=[('PACIENTE', 'Paciente / Tutor'), ('ESPECIALISTA', 'Especialista Clínico'), ('ADMINISTRADOR', 'Administrador')], default='PACIENTE', max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('rut', models.CharField(blank=True, max_length=12, verbose_name='RUT')),
                ('nombre_tutor', models.CharField(blank=True, max_length=120, verbose_name='nombre del tutor')),
                ('telefono_tutor', models.CharField(blank=True, max_length=20, verbose_name='teléfono del tutor')),
                ('edad', models.PositiveIntegerField(blank=True, default=18, null=True, verbose_name='edad')),
                ('fecha_consentimiento', models.DateTimeField(blank=True, null=True, verbose_name='fecha consentimiento ley 19.628 / 21.719')),
                ('pin_seguridad', models.CharField(default='1234', help_text='PIN de 4 dígitos para desbloquear la ficha clínica y diagnósticos', max_length=4, verbose_name='PIN de seguridad de ficha')),
                ('prefijo', models.CharField(blank=True, default='Dra.', max_length=15, verbose_name='título / prefijo')),
                ('especialidad', models.CharField(blank=True, max_length=120, verbose_name='especialidad')),
                ('biografia', models.TextField(blank=True, verbose_name='biografía clínica')),
                ('dias_atencion', models.CharField(blank=True, default='Lunes a Viernes', max_length=120, verbose_name='días de atención')),
                ('registro_minsal', models.CharField(blank=True, max_length=50, verbose_name='registro prestador de salud')),
                ('color_avatar', models.CharField(default='#d6e8f8', max_length=10, verbose_name='color de avatar')),
                ('iniciales', models.CharField(blank=True, max_length=5, verbose_name='iniciales')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('correo', models.CharField(blank=True, max_length=254)),
                ('accion', models.CharField(max_length=60)),
                ('detalle', models.CharField(blank=True, max_length=300)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
