# Generated by Django 5.2.17 on 2026-10-09 03:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VACACIONES', 'Solicitud de Vacaciones / Días Libres'), ('AGENDA', 'Ajuste de Horarios y Disponibilidad'), ('ADMINISTRATIVA', 'Consulta Administrativa o Insumos Clínicos'), ('URGENCIA', 'Notificación de Urgencia Clínica')], default='VACACIONES', max_length=30)),
                ('asunto', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False, verbose_name='atendido por administración')),
            ],
            options={
                'verbose_name': 'solicitud a administración',
                'verbose_name_plural': 'solicitudes a administración',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEA Nivel 1', 'TEA Nivel 1'), ('TEA Nivel 2', 'TEA Nivel 2'), ('Sensibilidad Auditiva', 'Sensibilidad Auditiva'), ('Integración Sensorial', 'Integración Sensorial'), ('TDAH', 'Evaluación TDAH'), ('Evaluación Conductual', 'Evaluación Conductual'), ('Fonoaudiología', 'Fonoaudiología'), ('Neurología', 'Neurología Pediátrica'), ('Primera consulta', 'Primera Consulta'), ('Otro', 'Otro informe clínico')], default='TEA Nivel 1', max_length=60)),
                ('titulo', models.CharField(max_length=150)),
                ('observaciones', models.TextField(blank=True, help_text='Notas clínicas, estímulos sensoriales evaluados y adaptaciones sugeridas', verbose_name='observaciones clínicas y recomendaciones')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='diagnosticos/')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('visible_para_paciente', models.BooleanField(default=True, help_text='Indica si el paciente puede visualizar este informe desde su Ficha', verbose_name='visible para el paciente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_relacionados', to='agenda.cita')),
            ],
            options={
                'verbose_name': 'diagnóstico sensorial',
                'verbose_name_plural': 'diagnósticos sensoriales',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
    ]
